database:
   dialect: postgres
   datasource: user=easymobile password=easymobile00 dbname=easymobile host=localhost port=5432 sslmode=disable
   showsql: true
   pool:
      min: 1
      max: 1
security:
   framedeny: true
   contenttypenosniff: true
   browserxssfilter: true
   contentsecuritypolicy: "default-src 'self'"
