database:
    datasource: user=ges password=ges00 dbname=ges host=localhost port=5432 sslmode=disable
    showsql: true
    pool:
        min: 1
        max: 1
certs:
   private: ges_pvt.pem
   public: ges_pub.pem